---
- hosts: nxos
  name: Configure Vlan
  gather_facts: no

  tasks:
    - name: NXOS Vlan config
      nxos_vlan:
        vlan_id: 100
        admin_state: up
        name: ansible_vlan
cisco@server-1:~/cluer_ansible_2019$ cat ios_config.yml
---
- name: Configure an ACL
  hosts: routers
  gather_facts: no
  connection: network_cli

  tasks:
  - name: configure interface settings
    ios_config:
      lines:
        - 10 permit ip host 192.0.2.1 any log
        - 20 permit ip host 192.0.2.2 any log
        - 30 permit ip host 192.0.2.3 any log
        - 40 permit ip host 192.0.2.4 any log
        - 50 permit ip host 192.0.2.5 any log
      parents: ip access-list extended test
      before: no ip access-list extended test
      match: exact
